matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
      install: brew update python
      before_script: cd ./src && make && cd ..
      script: python3 RunTests.py

before_install:
    - eval "${MATRIX_EVAL}"
