matrix:
    include:
        - os: linux
            env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
            addons:
                 apt:
                    packages:
                        - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
          install:
              - sudo apt-get install python3
          before_script:
              - cd src/ && make && cd ..
          script:
              python3 RunTests.py
              
        - os: osx
          env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
          compiler:
              - clang
          install:
              - brew upgrade python
          before_script:
              - cd src/ && make cd ..
          script:
              python3 RunTests.py

