matrix:
    inlcude:
        - language: cpp
          os: osx
          compiler:
            - gcc
            - clang
          before_script:
            - cd src/ && make
          script:
            - python3 RunTests.py
