matrix:
    include:
        - language: cpp
        - os: linux
          addons:
               apt:
                   sources:
                    - ubuntu-toolchain-r-test
                   packages:
                    - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          compiler:
              - gcc
          install:
              - sudo apt-get update
              - sudo apt-get install python3
          before_script:
              - cd src/ && make && cd ..
          script:
              python3 RunTests.py
              
        - language: cpp
        - os: osx
          env:
               - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
          compiler:
              - gcc
              - clang
          install:
              - brew upgrade python
          before_script:
              - cd src/ && make cd ..
          script:
              python3 RunTests.py
         
before_install:
    - eval "${MATRIX_EVAL}"
