matrix:
    include:
        - language: cpp
          os: linux
          addons:
               apt:
                   sources:
                    - ubuntu-toolchain-r-test
                   packages:
                    - g++-6
          env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
          compiler:
              - gcc
          install:
              - sudo apt-get update
              - sudo apt-get install python3
          before_script:
              - cd src/ && make
          script:
              python3 RunTests.py
              
        - language: cpp
          os: osx
          env:
               - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"
          compiler:
              - gcc
              - clang
          install:
              - brew upgrade python
          before_script:
              - cd src/ && make
          script:
              python3 RunTests.py
         
